// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQQHjZv5hkliO5pIlYQaYC4hf57iRqPTk',
    appId: '1:94176249472:web:c8816f6d08634f389c0865',
    messagingSenderId: '94176249472',
    projectId: 'wallify-e6f7f',
    authDomain: 'wallify-e6f7f.firebaseapp.com',
    storageBucket: 'wallify-e6f7f.appspot.com',
    measurementId: 'G-C8YJZZJYFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbLV037L-CcAuBNEHFcV14KS4epSyHRBM',
    appId: '1:94176249472:android:5e26dc55842f722b9c0865',
    messagingSenderId: '94176249472',
    projectId: 'wallify-e6f7f',
    storageBucket: 'wallify-e6f7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBahHRVxOD7TW0ezwG3FWEVGyhlk2Lqpg0',
    appId: '1:94176249472:ios:79f48e207015178a9c0865',
    messagingSenderId: '94176249472',
    projectId: 'wallify-e6f7f',
    storageBucket: 'wallify-e6f7f.appspot.com',
    iosBundleId: 'com.example.wallifyUi.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBahHRVxOD7TW0ezwG3FWEVGyhlk2Lqpg0',
    appId: '1:94176249472:ios:79f48e207015178a9c0865',
    messagingSenderId: '94176249472',
    projectId: 'wallify-e6f7f',
    storageBucket: 'wallify-e6f7f.appspot.com',
    iosBundleId: 'com.example.wallifyUi.RunnerTests',
  );
}
